name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'  # Matches v1.2.3, etc.

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # required for trusted publishing
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip build

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
